### ISSUE TITLE
Github Actions depolyment support?

### ISSUE THREAD

**Issue by katopz** [skymethod/denoflare#31]
Did we have `Github Actions` support? or maybe an example/tuts for how to do this.
I can see https://github.com/cloudflare/wrangler-action but not sure that I need to tweak some or it's just work for denoflare.

Great project btw.

**Comment by johnspurlock-skymethod** [comment]
Personally, since Deno is so flexible in terms of deployment, I usually just use a simple actions workflow that does a `actions/checkout@v3`, then a `./deploy.sh` step that downloads Deno and `deno run`s denoflare from a url (no install needed) with the `push` command.

Example deploy.sh
```
#!/bin/sh

# abort on any non-zero exit code
set -e

# ensure required environment variables are defined
if [ -z "$CF_ACCOUNT_ID" ] || [ -z "$CF_API_TOKEN" ] || [ -z "$CF_CUSTOM_DOMAIN" ] || [ -z "$CF_SCRIPT_NAME" ]; then
  echo "\$CF_ACCOUNT_ID, \$CF_API_TOKEN, \$CF_CUSTOM_DOMAIN, and \$CF_SCRIPT_NAME are required"
  exit 1
fi

# install deno
DENO_VERSION="v1.27.1"
DENOFLARE_VERSION="v0.5.9"
curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=./deno-$DENO_VERSION sh -s $DENO_VERSION

# run unit tests as a sanity check
NO_COLOR=1 DENO_VERSION=$DENO_VERSION ./deno-$DENO_VERSION/bin/deno test

# denoflare push the worker script to cloudflare
NO_COLOR=1 DENO_VERSION=$DENO_VERSION DENOFLARE_VERSION=${DENOFLARE_VERSION} ./deno-$DENO_VERSION/bin/deno run --unstable --allow-all https://raw.githubusercontent.com/skymethod/denoflare/$DENOFLARE_VERSION/cli/cli.ts \
push ./worker.ts --account-id $CF_ACCOUNT_ID --api-token $CF_API_TOKEN --custom-domain $CF_CUSTOM_DOMAIN --name $CF_SCRIPT_NAME \
--text-binding ... # whatever worker environment var bindings you need
```

I'm assuming if you did want a formal custom action for denoflare, you'd primarily be interested in this `denoflare push` scenario, right?  It would basically wrap something like the above under the hood.

**Comment by katopz** [comment]
`denoflare push` sound cool to me, will try. Thanks for the heads up!
